# Deskripsi Tugas

Pada tugas pratikum ini Anda akan menggunakan data "Wisconsin Breast Cancer". Data tersebut terdiri dari 569 data yang digunakan untuk mendiagnonis jenis kanker Malignant (M) dan Benign (B). Tugas Anda adalah,

In [13]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

dpath = 'wbc.csv'
df = pd.read_csv(dpath)
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

1. Pisahkan antara variabel yang dapat digunakan dan variabel yang tidak dapat digunakan.

In [14]:
df = df[['diagnosis', 'radius_mean', 'texture_mean', 'area_mean', 'radius_se', 'texture_se', 'area_se', 'radius_worst', 'texture_worst', 'area_worst',]]
df.head()

,diagnosis,radius_mean,texture_mean,area_mean,radius_se,texture_se,area_se,radius_worst,texture_worst,area_worst
0,M,17.99,10.38,1001.0,1.0950,0.9053,153.40,25.38,17.33,2019.0
1,M,20.57,17.77,1326.0,0.5435,0.7339,74.08,24.99,23.41,1956.0
2,M,19.69,21.25,1203.0,0.7456,0.7869,94.03,23.57,25.53,1709.0
3,M,11.42,20.38,386.1,0.4956,1.1560,27.23,14.91,26.50,567.7
4,M,20.29,14.34,1297.0,0.7572,0.7813,94.44,22.54,16.67,1575.0

2. Lakukan proses encoding pada kolom "diagnosis".

In [15]:
le = LabelEncoder() # Membuat objek dari encoder
df['diagnosis'] = le.fit_transform(df['diagnosis']) #proses encoding
df.head()

,diagnosis,radius_mean,texture_mean,area_mean,radius_se,texture_se,area_se,radius_worst,texture_worst,area_worst
0,1,17.99,10.38,1001.0,1.0950,0.9053,153.40,25.38,17.33,2019.0
1,1,20.57,17.77,1326.0,0.5435,0.7339,74.08,24.99,23.41,1956.0
2,1,19.69,21.25,1203.0,0.7456,0.7869,94.03,23.57,25.53,1709.0
3,1,11.42,20.38,386.1,0.4956,1.1560,27.23,14.91,26.50,567.7
4,1,20.29,14.34,1297.0,0.7572,0.7813,94.44,22.54,16.67,1575.0

3. Lakukan proses standarisasi pada semua kolom yang memiliki nilai numerik.

In [16]:
std = StandardScaler()
df['radius_mean'] = std.fit_transform(df[['radius_mean']])
df['texture_mean'] = std.fit_transform(df[['texture_mean']])
df['area_mean'] = std.fit_transform(df[['area_mean']])
df['radius_se'] = std.fit_transform(df[['radius_se']])
df['texture_se'] = std.fit_transform(df[['texture_se']])
df['area_se'] = std.fit_transform(df[['area_se']])
df['radius_worst'] = std.fit_transform(df[['radius_worst']])
df['texture_worst'] = std.fit_transform(df[['texture_worst']])
df['area_worst'] = std.fit_transform(df[['area_worst']])
df.head()

,diagnosis,radius_mean,texture_mean,area_mean,radius_se,texture_se,area_se,radius_worst,texture_worst,area_worst
0,1,1.097064,-2.073335,0.984375,2.489734,-0.565265,2.487578,1.886690,-1.359293,2.001237
1,1,1.829821,-0.353632,1.908708,0.499255,-0.876244,0.742402,1.805927,-0.369203,1.890489
2,1,1.579888,0.456187,1.558884,1.228676,-0.780083,1.181336,1.511870,-0.023974,1.456285
3,1,-0.768909,0.253732,-0.764464,0.326373,-0.110409,-0.288378,-0.281464,0.133984,-0.550021
4,1,1.750297,-1.151816,1.826229,1.270543,-0.790244,1.190357,1.298575,-1.466770,1.220724

4. Lakukan proses stratified split data untuk membuat data latih dan data uji dengan rasio 80:20.

In [18]:
df_train, df_test = train_test_split(df, test_size=0.2, random_state=0, stratify=df['diagnosis'])

print(f'Jumlah data asli: {df.shape[0]}')
print(f'Jumlah data train: {df_train.shape[0]}')
print(f'Jumlah data test: {df_test.shape[0]}')

print('====================================')
print(f'Jumlah label data asli:\n{df.diagnosis.value_counts()}')
print(f'Jumlah label data train:\n{df_train.diagnosis.value_counts()}')
print(f'Jumlah label data test:\n{df_test.diagnosis.value_counts()}')

Jumlah data asli: 569
Jumlah data train: 455
Jumlah data test: 114
====================================
Jumlah label data asli:
diagnosis
0    357
1    212
Name: count, dtype: int64
Jumlah label data train:
diagnosis
0    285
1    170
Name: count, dtype: int64
Jumlah label data test:
diagnosis
0    72
1    42
Name: count, dtype: int64